apiVersion: v1
kind: Service
metadata:
  name: generator
  labels:
    app: generator
spec:
  ports:
  - port: 1234 
    name: http
  selector:
    app: generator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: generator-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: generator
        version: v1
    spec:
      containers:
      - name: generator
        image: ecida/1_generator
        env:
        - name: SINK
          value: "http://router"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always

---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: router
---
apiVersion: v1
kind: Service
metadata:
  name: output
  labels:
    app: output
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: output
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: output-json
  labels:
    version: json
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: output
        version: json
    spec:
      containers:
      - name: outputjson
        image: ecida/3_outputjson
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: output-csv
  labels:
    version: csv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: output
        version: csv
    spec:
      containers:
      - name: outputcsv
        image: ecida/3_outputcsv
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: transformer
  labels:
    app: transformer
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: transformer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transformer-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transformer
        version: v1
    spec:
      containers:
      - name: transformer
        image: ecida/2_transformer
        env:
        - name: SINK
          value: "http://router"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3000
